services:
  - type: web
    name: nexus-connect-backend
    env: java
    region: oregon
    plan: free
    rootDir: backend-java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/nexus-connect-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: MONGODB_URI
        sync: false # You will enter this in the Render Dashboard
      - key: PORT
        value: 8080
      - key: SOCKET_PORT
        value: 10000 # Different port, though Free Tier may block this access.
