services:
  - type: web
    name: aws-cloud-connect-server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        sync: false
    buildCommand: npm install
    startCommand: npm start
    region: oregon
